In [1]:
import numpy as np
import pandas as pd

baseDeDados = pd.read_csv('svbr.csv', delimiter=';')
x = baseDeDados.iloc[:,:].values

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='median') # aqui faz a media de todos os valores nulos de uma vez
imputer = imputer.fit(x[:,1:3]) # pega a coluna 2 e 3 pq a 1 e uma str
# 1 pq e o indice da segunda coluna e 3 pq na ultima sempre se acresenta mais um
x = imputer.transform(x[:,1:3]).astype(str)

display(x)

array([['13438.0', '406590.0'],
       ['35241.0', '868235.0'],
       ['31680.0', '2856508.0'],
       ['25100.0', '150000.0'],
       ['32788.0', '1575456.0'],
       ['65453.0', '1667892.0'],
       ['12000.0', '171361.0'],
       ['161951.0', '11027386.0'],
       ['78876.0', '6226235.0'],
       ['274196.0', '30166457.0'],
       ['13148.0', '250020.0'],
       ['72425.0', '7551491.0'],
       ['7858.0', '43662.0'],
       ['110549.0', '4151548.0'],
       ['11188.0', '541832.0'],
       ['5299.0', '44312.0'],
       ['56006.0', '1329268.0'],
       ['45756.0', '1825724.0'],
       ['1423056.0', '93036517.0'],
       ['129466.0', '5027880.0'],
       ['137409.0', '5363423.0'],
       ['18404.0', '1427977.0'],
       ['42063.0', '1111334.0'],
       ['648892.0', '22555134.0'],
       ['135118.0', '3375528.0'],
       ['9118.0', '683190.0'],
       ['374057.0', '12139385.0'],
       ['88211.0', '1616496.0'],
       ['49797.0', '1595976.0'],
       ['321068.0', '26277335.0'],
       

In [2]:
import numpy as np
import pandas as pd

In [3]:
from sklearn.impute import SimpleImputer

baseDeDados = pd.read_csv('admission.csv', delimiter=';')
x = baseDeDados.iloc[:,:-1].values
y = baseDeDados.iloc[:,-1].values
# : todos , e igal x e y em grafico(x = linhas y = colunas), numero positivo apartir de negativo menos de

imputer = SimpleImputer(missing_values=np.nan, strategy='median')
imputer = SimpleImputer(missing_values=np.nan, strategy='median')
imputer = imputer.fit(x[:,1:])


In [4]:
from sklearn.preprocessing import LabelEncoder # tranforma str em legendas de numeros para poder ser treinar
LabelEncoder_x = LabelEncoder()
x[: , 0] = LabelEncoder_x.fit_transform(x[: , 0]) # faz a codificaçao e armazena na sua coluna
print(x)
# porem assim nao exclui como o .drop, o q pode atrapalar

[[6 337 118 4 4.5 4.5 9.65 1]
 [0 324 107 4 4.0 4.5 8.87 1]
 [5 316 104 3 3.0 3.5 8.0 1]
 [1 322 110 3 3.5 2.5 8.67 1]
 [8 314 103 2 2.0 3.0 8.21 0]
 [4 330 115 5 4.5 3.0 9.34 1]
 [3 321 109 3 3.0 4.0 8.2 1]
 [2 308 101 2 3.0 4.0 7.9 0]
 [7 302 102 1 2.0 1.5 8.0 0]]


In [5]:
x = x[: , 1:] #conta apartir do indice 1 excluindo a primeira coluna (tipo um .drop)
d =pd.get_dummies(x[: , 0]) # desse modo transforma a coluna em dados binarios para a maquinica nao alterar seu resultado
# porem assim vai tranformar em uma coluna cada dado
x = np.insert(x , 0 , d.values , axis=1)

print(x)

[[False False False False False False False False True 337 118 4 4.5 4.5
  9.65 1]
 [False False False False False False False True False 324 107 4 4.0 4.5
  8.87 1]
 [False False False False True False False False False 316 104 3 3.0 3.5
  8.0 1]
 [False False True False False False False False False 322 110 3 3.5 2.5
  8.67 1]
 [False False False False False False True False False 314 103 2 2.0 3.0
  8.21 0]
 [False False False True False False False False False 330 115 5 4.5 3.0
  9.34 1]
 [False True False False False False False False False 321 109 3 3.0 4.0
  8.2 1]
 [False False False False False True False False False 308 101 2 3.0 4.0
  7.9 0]
 [True False False False False False False False False 302 102 1 2.0 1.5
  8.0 0]]


In [6]:
from sklearn.model_selection import train_test_split

xTrain, xTest, yTrain, yTest = train_test_split(x, y, test_size = 0.2)
print(xTrain)

[[False False False False False False False True False 324 107 4 4.0 4.5
  8.87 1]
 [False False False False False False False False True 337 118 4 4.5 4.5
  9.65 1]
 [False False False False False True False False False 308 101 2 3.0 4.0
  7.9 0]
 [False False False True False False False False False 330 115 5 4.5 3.0
  9.34 1]
 [False False True False False False False False False 322 110 3 3.5 2.5
  8.67 1]
 [False False False False True False False False False 316 104 3 3.0 3.5
  8.0 1]
 [False False False False False False True False False 314 103 2 2.0 3.0
  8.21 0]]


In [7]:
# normalisando dados com o mesmo peso pq se uma coluna tiver o valor
# muito maior q os outros o sisteama vai dar um peso mais pra aquele dado em sua decisao

from sklearn.preprocessing import StandardScaler

Scalerx = StandardScaler()
xTrain = Scalerx.fit_transform(xTrain)#fit.transform faz a diferença e ja aplica
xTest = Scalerx.fit_transform(xTest)

print(xTrain)

[[ 0.          0.         -0.40824829 -0.40824829 -0.40824829 -0.40824829
  -0.40824829  2.44948974 -0.40824829  0.26504327 -0.21802571  0.69337525
   0.59160798  1.27475488  0.33338707  0.63245553]
 [ 0.          0.         -0.40824829 -0.40824829 -0.40824829 -0.40824829
  -0.40824829 -0.40824829  2.44948974  1.68380429  1.64730538  0.69337525
   1.18321596  1.27475488  1.58876185  0.63245553]
 [ 0.          0.         -0.40824829 -0.40824829 -0.40824829  2.44948974
  -0.40824829 -0.40824829 -0.40824829 -1.48112414 -1.23547904 -1.24807544
  -0.59160798  0.58834841 -1.22778412 -1.58113883]
 [ 0.          0.         -0.40824829  2.44948974 -0.40824829 -0.40824829
  -0.40824829 -0.40824829 -0.40824829  0.91985605  1.13857872  1.66410059
   1.18321596 -0.78446454  1.08983085  0.63245553]
 [ 0.          0.          2.44948974 -0.40824829 -0.40824829 -0.40824829
  -0.40824829 -0.40824829 -0.40824829  0.04677234  0.29070095 -0.2773501
   0.         -1.47087101  0.01149611  0.63245553]
 [ 0. 